### ISSUE TITLE
Missing header "gtype-desc.h"

### ISSUE THREAD

**Issue by been-jamming** [debrouxl/gcc4ti#15]
On arch linux with gcc 12.2.0, I am attempting to create a PKGBUILD so that I can put gcc4ti on the AUR. Running the installation script manually, I am able to install the software using a custom prefix. I am having problems executing the (slightly modified) install script from inside of the `build` function in my PKGBUILD. Here is the relevant bash function:

```
build(){
        cd "$pkgname/trunk/tigcc-linux/scripts"
        ./updatesrc
        ./package_src
        cd ../gcc4ti-0.96b11/scripts
        cp ../../../../../../Install.sh .
        PREFIX_GCC4TI="$(realpath installation)" ./Install.sh
}
```

The function navigates to `trunk/tigcc-linux/scripts` and executes `updatescr` and `package_src` as instructed. Then it navigates to `trunk/tigcc-linux/gcc4ti-0.96b11/scripts`. It copies my modified installation script (in which I've copied the original installation script and only removed the input prompts) into the scripts directory. It runs the install script with a prefix indicating a directory in the scripts directory - so it should install tigcc to `trunk/tigcc-linux/gcc4ti-0.96b11/scripts/installation`.

When running the build function, binutils compiles, but gcc fails to compile. The error is:
```fatal error: gtype-desc.h: No such file or directory```
After manually adding this file and trying again, I've seen that many more files are missing. The compilation succeeds, however, if inside of the build function I run the install script with `sudo`, so I suspect it's a permissions problem. Note that I don't need to use sudo to manually use the installation script.

Unfortunately, since I don't know enough about `makepkg`, I can't give the exact conditions required to reproduce this issue. Is there any reason why the install script should stop working inside of my `build` function, or when run from makepkg in general?

**Comment by debrouxl** [comment]
Several notes:
* the local binutils and GCC build scripts (launch.binutils, launch.gcc) have always expected the build to fail, because that's an effect of the local patches, so they ignore errors (`make -i`) and carry on. The build really shouldn't outright stop. Where does it really stop for you when running from that function and not using `sudo` ?
* interactive scripts such as `Install` can usually be made non-interactive by sending commands on stdin, using a multi-line echo, a here document, or something along those lines. I don't seem to have done it locally for GCC4TI, but I did it for other installers over time. IOW, you certainly don't need to use a modified installation script :)
* I don't know enough about `makepkg` either, but in general, packaging tools often run the build in special environments. The scripts called by the top-level install script are definitely designed to perform both the build and the install in a single step; that can be fixed, but I never spent time on code adding support for at least `su`, `doas` and unfortunately `sudo` privilege elevation methods (`sudo` is an endless stream of critical security vulnerabilities, too bad it's so widely used on Linux) - which would benefit the TILP & TIEmu install scripts, too.
* a word of caution: using such recent GCC toolchains to build such old code bases as these heavily patched forks of binutils 2.16.1 & GCC 4.1.2 may yield binaries which miscompile source code.
The newer the GCC toolchain, the less tolerant to optimization-unsafe or non-portable code it is... and even without the local patch, 4.1-era GCC has such code. There's no telling that the binaries successfully built by GCC 12.x for Linux aren't affected by issues such as the one mentioned in the top-level README, GCC 4.9 targeting Win32 producing broken floating-point support, or other previously unknown correctness issues.
At least, your report shows that the build of these old forks of binutils & GCC aren't further broken by GCC 12, i.e. that the build fixes created for older GCC versions are still useful.

**Comment by been-jamming** [comment]
The build fails in `Install_step_2` while calling the `laungh.gcc` scripts and `../../download/gcc.ti/configure` scripts. The last script attempts to call the `install` command on a file which doesn't exist. I've attached the full build log here. Search for `fatal error` to see the compilation errors:
[makepkg_output.txt](https://github.com/debrouxl/gcc4ti/files/9847653/makepkg_output.txt)

Your second point is a good idea. I will do that instead of modifying the install script.

For your third point, makepkg has 2 main steps: a build step and a package step. The build step is designed to build the software without requiring root permission, and the package step enters a fakeroot in which the software gets installed into directory mimicking the file system. I figured I could build the software and install it into a custom directory during the build step, and manually copy over the files into the correct directories during the install step.

Ideally, which version of gcc should I use to compile everything? I should have no trouble adding that version as a make dependency.

**Comment by debrouxl** [comment]
Thanks for the complete output. I see a `-Werror=format-security` become default - which is a good thing ! - and an ancient, dirty code base which needs a bunch of new fixes, after all... Boo.

What if you try to do everything inside the package step ? An alternative is, of course, to refactor the GCC4TI build scripts to split the build and install phases, but that's some amount of boring work of limited practical usefulness.

Using an older version of GCC (I couldn't tell you which one exactly) to build this ancient fork is at best a short-term workaround and bandaid for the proper solution of making the code base buildable by recent - and future - versions of GCC, by patching select places once more. TI-68k native code development in C is long past life support, though... upgrading the toolchain, or worse, developing a new one, is way too much work for way too few users.
I rewrote libticalcs' TI-68k ROM dumper in pure assembly because it was the right thing to do, going forward: no need to depend on this ancient and increasingly unsupportable GCC fork, or a recent GCC which is known to generate slower code ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40454 ), crash and/or generates invalid code ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88589 ).

**Comment by been-jamming** [comment]
Good news! I got things to work. As I typed out my comment, I realized what was happening is that sudo creates a new environment for the command to run in. The environment variables set by makepkg must have been messing with the build script. Inside of the build function, I am now executing:

```
env -i PATH="$PATH" PREFIX_GCC4TI="$(realpath installation)" "./Install.sh"
```

Even if it's only a temporary fix, requiring a certain version of gcc to build will probably be good to do if other people with possibly different versions installed are going to try to install the package from the AUR. I might play around with using different versions of gcc to build and see which one works the best.

I think I remember asking you on reddit about how binaries on the Ti89 are stored. I did end up making my own mini C compiler. I might redo the compiler later to use less resources and support various targets. The only obstruction would still be outputting the binaries in a correct format because I wasn't able to gather much from our conversation at the time. It might be nice to have a project which is independent of these massive toolchains, and there's even the possibility of using the compiler on the calculator. Is there a good way for me to find a detailed description of how the Ti89 loads assembly programs to be run and how the .89z file format works?

**Comment by been-jamming** [comment]
Another thing I forgot to mention is that makepkg is now telling me that the compiled binaries contain references to the original directory I told the install script to install to. I checked, and these aren't symlinks or hardlinks. Will the installation break if I move these binaries around?

**Comment by debrouxl** [comment]
In Debian 7 / GCC 4.6 and Debian 8 / GCC 4.9 times, there were no known compiler and linker issues for a native Linux build. However, distributions rightfully do no longer package such old toolchains, which may themselves not build with the newest toolchains, either - maybe compiling a host/cross-GCC 4.6 requires building say, host GCC 6 or 7 first.
In general, proper regression testing requires gathering hundreds of programs, building them, and testing them - multiple times, for every host toolchain you want to test. Not that the maintainer of GCC4TI's ancestor performed proper regression testing on his side when he upgraded GCC, but still.
In your case, same cross-compiler version compiled by multiple native/cross-toolchain versions, finding whether and which generated TI-68k binaries change when the native/cross-toolchain used for compiling the cross-compiler may do a large part of the regression testing job, _if_ there are no regressions. You'd still have to gather a large number of programs, and if you want to be able to perform automated regression testing on them, make them buildable with tprbuilder. Sadly, many aren't, because they're designed to work only with the IDE and its... peculiar... virtual folder thing, which tprbuilder fortunately does not attempt to emulate, and/or absolute paths on the author's Windows system.
Any way you look at it, it's a huge amount of work, for very few potential users... which is why I haven't done it. Over the years, I've spent significantly more time on libti*/gfm/tilp than on GCC4TI, because they have many more potential users, and as such, time spent on them is therefore more impactful for real users in the real world. Over the past year, I've spent significantly more time working on, or testing, another code base than libti*/gfm/tilp, because it has many more potential users.

The 92+/89/V200/89T AMS native ASM and Exec string format is as follows:
* 2 bytes: header containing total variable size - 2, like other AMS variables;
* binary program data;
* pairs of (2 bytes offset of target for relocation, 2 bytes offset of program location to be relocated);
* 1 byte: 0xF3 (ASM_TAG).

The AMS relocation code processes the relocation table from the end downwards and stops when it encounters a 0x0000 offset of program relocation. That's why Exec strings need to contain an extra 0000, e.g. Exec "4E444E750000" (trap #4; rts, which is a simple way to power off the calculator).

There already exist multiple on-calc C compilers; even back when TI-68k programming was popular enough, they had limited functionality (C dialect support, source program size and complexity, etc.) and poor stability, due to the low amount of memory available on the platform. Overt hostility of the dominant toolchain maker did not help them either, that's for sure.
In order to go beyond the educational work for yourself - which is a laudable goal, don't get me wrong ! - and provide something that the scarce remaining TI-68k programmers would want to use, what you bring to the table would need to be measurably better than the existing on-calc toolchains.
You'd probably have more fun - and learn more, too - by sticking to the computer side for your toolchain ;)

If `makepkg` reports references to the original directory (RPATH, RUNPATH or others), it's certainly right, and yes, the install could break if you move these binaries around. Better build them into the desired target prefix.

**Comment by been-jamming** [comment]
It seems that the compilation flags in the build script don't affect the way certain binaries link, and this is what was giving me the error that they weren't relocatable. However, it doesn't seem like these binaries are used by the compiler. I've added gcc4ti to the [aur](https://aur.archlinux.org/packages/gcc4ti).

**Comment by kkofler** [comment]
> TI-68k native code development in C is long past life support, though...

This is an outright declaration of bankruptcy. If that is your assessment of the state it is in, you can shut down the GCC4TI project completely.

If a GCC built with a recent host GCC is not working properly, using a binary built with an old GCC can be a workaround. Either an old binary (such as the 32-bit binary tarball of the original TIGCC on http://tigcc.ticalc.org/linux.html – 64-bit binaries are only available as RPMs there at this time though), or build a new one in an old enough chroot. E.g., `mock -r eol/epel-5-x86_64 gcc4ti-*.src.rpm` on a Fedora or AlmaLinux system.

> Another thing I forgot to mention is that makepkg is now telling me that the compiled binaries contain references to the original directory I told the install script to install to. I checked, and these aren't symlinks or hardlinks. Will the installation break if I move these binaries around?

At least in the original TIGCC, the `tigcc` executable actually passes arguments to the invoked `gcc` overriding the compiled-in directories, so it should be safely relocatable. Though I have not checked whether that is working properly in this fork. (@debrouxl has changed some things in the way the internally invoked executables are installed, so it may or may not have been broken.)

**Comment by kkofler** [comment]
And we would not be struggling with issues when compiling an ancient cross GCC with a much newer host GCC if someone had worked on keeping the patched cross GCC up to date, something you always filed off as not useful (and I personally definitely would have been more motivated to do it if TIGCC had not been forked by this hostile project). Any regressions in newer GCC versions would also have been much easier to track down when going from version n to n+1 than when going from version n to n+bazillions.
